#!/usr/bin/env bash

SKETCHYBAR_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$SKETCHYBAR_DIR/plugins"

# Source colors
source "$SKETCHYBAR_DIR/colors"

MONOSPACE_FONT='DejaVuSansMono Nerd Font Mono'
SANS_FONT='DejaVuSansMono Nerd Font Mono'

#
# Bar settings
#

sketchybar --bar    height=20           \
                    blur_radius=70      \
                    position=top        \
                    padding_left=5      \
                    padding_right=5     \
                    margin=5            \
                    y_offset=2          \
                    corner_radius=6     \
                    sticky=on           \
                    color="$SK_BAR"


#
# Item defaults
#

sketchybar --default    updates=when_shown                                  \
                        drawing=on                                          \
                        icon.font="$MONOSPACE_FONT:Book:13.0"               \
                        icon.color="$SK_TEXT"                               \
                        label.font="$SANS_FONT:Book:12"                     \
                        label.color="$SK_TEXT"                              \
                        label.padding_left=2                                \
                        label.padding_right=2                               \
                        icon.padding_left=3                                 \
                        icon.padding_right=3                                \
                        background.padding_left=5                           \
                        background.padding_right=5                          \
                        background.corner_radius=8                          \
                        background.height=20                                \


#
# Left items
#

## Space indicators

SPACE_ICONS=("Ⅰ" "Ⅱ" "Ⅲ" "Ⅳ" "Ⅴ" "Ⅵ" "Ⅶ" "Ⅷ" "Ⅸ")
#SPACE_ICONS=("一" "二" "三" "四" "五" "六" "七" "八" "九" "十")
#SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
#SPACE_ICONS=("A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "L")
#SPACE_ICONS=("🀙" "🀚" "🀛" "🀜" "🀝" "🀞" "🀟" "🀠" "🀡")
#SPACE_ICONS=("𝟏" "𝟐" "𝟑" "𝟒" "𝟓" "𝟔" "𝟕" "𝟖" "𝟗")
SPACES=()

for i in "${!SPACE_ICONS[@]}"
do
    sid=$((i + 1))
    SPACES+=("space.$sid")
    sketchybar  --add       space           space.$sid left                             \
                --set       space.$sid      associated_space=$sid                       \
                                            icon="${SPACE_ICONS[i]}"                    \
                                            icon.padding_left=9                         \
                                            icon.padding_right=9                        \
                                            icon.highlight_color="$SK_SPACE_HL_FG"      \
                                            background.padding_left=2                   \
                                            background.padding_right=2                  \
                                            background.color="$SK_SPACE_HL_BG"          \
                                            background.corner_radius=8                  \
                                            background.height=20                        \
                                            background.drawing=off                      \
                                            label.drawing=off                           \
                                            script="TEXT=$SK_SPACE_TEXT SPACE_OCCUPIED_FG=$SK_SPACE_OCCUPIED_FG $PLUGIN_DIR/space.sh"               \
                                            click_script="yabai -m space --focus $sid"
done

sketchybar --add            bracket         spaces_br "${SPACES[@]}"    \
           --set            spaces_br       background.color="$SK_ITEM_BG"


#
# Center items
#

## Focused app name
# sketchybar --add        item front_app      center                              \
#            --set        front_app           script="$PLUGIN_DIR/front_app.sh"   \
#                                             icon.drawing=off                    \
#            --subscribe  front_app           front_app_switched


#
# Right items
#

sketchybar --add        item            clock right                              \
           --set        clock           update_freq=1                            \
                                        label.font="$MONOSPACE_FONT:Book:12.0"   \
                                        script="$PLUGIN_DIR/clock.sh"            \
#                                       label.padding_left=8                     \
#                                       label.padding_right=8                    \
#                                       background.color="$SK_ITEM_BG"           \
#                                       icon.drawing=off                         \
#                                       icon=""                                 \
#                                       label.font="$MONOSPACE_FONT:Regular:13.0"    \
# \
#            --add        event           input_change 'AppleSelectedInputSourcesChangedNotification' \
#            --add        item            keyboard right                                              \
#            --set        keyboard        script="$PLUGIN_DIR/keyboard.sh"                            \
#                                         label.font="$MONOSPACE_FONT:Regular:14.5"                   \
#            --subscribe  keyboard        input_change                                                \
# \
#            --add        item            battery right                   \
#            --set        battery         script="BATTERY_LOW=$SK_BATTERY_LOW BATTERY_CHARGING=$SK_BATTERY_CHARGING $PLUGIN_DIR/battery.sh" \
#                                         update_freq=10                  \
#            --subscribe  battery         system_woke                     \
#            --subscribe  battery         system_woke battery_state_changed battery_level_changed
#            --add        event           battery_state_changed "UIDeviceBatteryStateDidChangeNotification" \
#            --add        event           battery_level_changed "UIDeviceBatteryLevelDidChangeNotification" \
# \
#            --add        item            wifi right                      \
#            --set        wifi            script="$PLUGIN_DIR/wifi.sh"    \
#                                         update_freq=10                  \

sketchybar --update
echo "sketchybar configuration loaded.."
