#!/usr/bin/env sh

#
# Theme & colors
#

# # Catppuccin v1
# text='C3BAC6' # gray2
# text='988BA2' # gray1
# black='1F1E2F'
# green='ABE9B3'
# purple='C9CBFF'
# blue='96CDFB'

# # Catppuccin mocha
# text='9399b2' # overlay2
# black='1F1E2F'
# green='a6e3a1'
# purple='b4befe'
# blue='89b4fa'
# # white='cdd6f4'

# Onedark
black='282D35'
text='979FAD'
space='5882CA'
green='98C379'
purple='C679DD'
blue='61AFEF'

# Fonts
ic_font="DejaVuSansMono Nerd Font Mono"
text_font="DejaVuSansMono Nerd Font Mono"


#
# Settings
#

spacebar -m config position                    bottom
spacebar -m config display                     main
spacebar -m config height                      15
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       off
spacebar -m config power                       off
spacebar -m config padding_left                15
spacebar -m config padding_right               15
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "$text_font:Regular:10"
spacebar -m config icon_font                   "$ic_font:Regular:10"
spacebar -m config background_color            0xff$black
spacebar -m config foreground_color            0xff$text
spacebar -m config power_icon_color            0xff$green
spacebar -m config battery_icon_color          0xff$text
spacebar -m config dnd_icon_color              0xff$purple
spacebar -m config clock_icon_color            0xff$text
spacebar -m config power_icon_strip              #     ﴞ ﴞ 
spacebar -m config space_icon                   # • ■
spacebar -m config space_icon_color            0xff$space
spacebar -m config space_icon_color_secondary  0xff78c4d4
spacebar -m config space_icon_color_tertiary   0xfffff9b0
#spacebar -m config space_icon_strip           A B C D E F G H I J L
#spacebar -m config space_icon_strip           🀙 🀚 🀛 🀜 🀝 🀞 🀟 🀠 🀡
spacebar -m config space_icon_strip           Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ
#spacebar -m config space_icon_strip            𝟏 𝟐 𝟑 𝟒 𝟓 𝟔 𝟕 𝟖 𝟗
#spacebar -m config space_icon_strip            一 二 三 四 五 六 七 八 九 十
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                   #   􀐫
spacebar -m config dnd_icon                     # 
spacebar -m config clock_format                "%R" # %R – %d.%m
spacebar -m config right_shell                 off
spacebar -m config right_shell_icon            ﬉ # ﬉
spacebar -m config right_shell_icon_color      0xff$text
# spacebar -m config right_shell_command         "env PATH='~/bin/:$PATH' getwifiname"
#spacebar -m config right_shell_command         "/Users/foreverd34d/bin/getwifiname"

echo "spacebar configuration loaded.."
