[manager]

prepend_keymap = [
  { on = [ "g", "d" ],       run = "cd ~/.dotfiles",           desc = "Go dotfiles" },
  { on = [ "g", "s" ],       run = "plugin zx-jump",           desc = "searchjump mode" },
]

append_keymap = [
  { on = [ "g", "D" ],       run = "cd ~/Downloads",           desc = "Go Downloads" },
  { on = [ "g", "p" ],       run = "cd ~/Project",             desc = "Go Project" },
  { on = [ "g", "-" ],       run = "cd -",                     desc = "Go back" },
  { on = [ "g", "/" ],       run = "cd --interactive",         desc = "Jump interactively" },
]
