#!/usr/bin/env sh

### Load scripting addition ###
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


### Settings ###
# External bar
yabai -m config external_bar all:22:0
# yabai -m config external_bar all:0:25

# Global settings
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.05
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Borders
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff81a1c1
yabai -m config normal_window_border_color   0x002e3440
yabai -m config insert_feedback_color        0xffd75f5f

# Mouse settings
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autoraise
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config window_placement             first_child # second_child
# yabai -m config window_topmost               on
yabai -m config layout                       float
yabai -m config top_padding                  04
yabai -m config bottom_padding               04
yabai -m config left_padding                 04
yabai -m config right_padding                04
yabai -m config window_gap                   04


### Rules ###
float_grid_xl=19:19:1:1:17:17
float_grid=9:9:1:1:7:7
yabai -m rule --add app="^Alacritty$"                             manage=off  grid=$float_grid_xl
yabai -m rule --add app="^System Preferences$"                    manage=off  grid=$float_grid
yabai -m rule --add app="^System Information$"                    manage=off  grid=$float_grid
yabai -m rule --add app="^Finder$"                                manage=off  grid=$float_grid
yabai -m rule --add app="^Notes$"                                 manage=off  grid=$float_grid
yabai -m rule --add app="^Activity Monitor$"                      manage=off  grid=$float_grid
yabai -m rule --add app="^Music$"                                 manage=off  grid=$float_grid
yabai -m rule --add label="App Store" app="^App Store$"           manage=off  grid=$float_grid
yabai -m rule --add app="^Calculator$"                            manage=off
yabai -m rule --add app="^Font Book$"                             manage=off
yabai -m rule --add app="^Archive Utility$"                       manage=off
yabai -m rule --add app="^Digital Colou?r Meter$"                 sticky=on
yabai -m rule --add label="LINE" app="^LINE$"                     manage=off  grid=$float_grid

### execute skhd ###
skhd &

### execute skhd ###
sketchybar &

### execute spacebar ###
#spacebar &
#
#SPACEBAR_HEIGHT=$(spacebar -m config height)
#if [ -z "$SPACEBAR_HEIGHT" ];then
#    SPACEBAR_HEIGHT=15
#fi
#yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

