zstyle :plugin:fast-syntax-highlighting theme "x"
typeset -g FAST_THEME_NAME="x"
: ${FAST_HIGHLIGHT_STYLES[xdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[xunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[xreserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xalias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xsuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xbuiltin]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xfunction]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xcommand]:=fg=180}
: ${FAST_HIGHLIGHT_STYLES[xprecommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[xhashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xpath]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[xpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[xglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[xglobbing-ext]:=fg=13}
: ${FAST_HIGHLIGHT_STYLES[xhistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[xsingle-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[xdouble-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[xback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[xsingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xdouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xdollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xback-or-dollar-double-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[xback-dollar-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[xassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[xredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[xcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[xvariable]:=fg=113}
: ${FAST_HIGHLIGHT_STYLES[xmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[xmathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[xmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[xassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[xfor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[xfor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xfor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[xexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[xhere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xhere-string-text]:=fg=18}
: ${FAST_HIGHLIGHT_STYLES[xhere-string-var]:=fg=cyan,bg=18}
: ${FAST_HIGHLIGHT_STYLES[xsecondary]:=default}
: ${FAST_HIGHLIGHT_STYLES[xcase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xcase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xcase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[xcorrect-subtle]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[xincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[xsubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xsubtle-bg]:=bg=18}
: ${FAST_HIGHLIGHT_STYLES[xpath-to-dir]:=fg=magenta,underline}
: ${FAST_HIGHLIGHT_STYLES[xpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[xbracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[xbracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[xbracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[xglobal-alias]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[xsubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xsingle-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xdouble-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[xdouble-paren]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xoptarg-string]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[xoptarg-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[xrecursive-base]:=none}
