# fix 0;10;1c
# https://github.com/microsoft/WSL/issues/5931
set -sg escape-time 50

# remap prefix to 'M-\'
unbind C-b
set -g prefix 'M-\'
bind-key 'M-\' send-prefix

# make delay shorter
#set -sg escape-time 0


#### key bindings ####

# reload config file
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# kill-session
bind C-d kill-session

# synchronize all panes in a window
# :setw synchronize-panes
#bind _ setw synchronize-panes

# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# enable mouse support for switching panes/windows
#set -g mouse-utf8 on
set -g mouse on

#### copy mode : vi ####
set-option -g mouse on
setw -g mode-keys vi
set-option -s set-clipboard off

# v to start copying
bind-key -T copy-mode-vi v send-keys -X begin-selection

# 
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle

# y as Enter
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Paste into the buffer with <prefix>+P (make sure that it’s uppercase P).
bind P paste-buffer

#### tpm ####
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# chang plugins install dir
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins/'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'jimeh/tmux-themepack'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.local/share/tmux/plugins/tpm/tpm'

set -g @themepack 'powerline/default/blue'

set -g status-bg colour240
set -g status-fg colour250
